if (NOT Fiesta_BUILD_LUA)
    find_package(Lua QUIET)
    if(LUA_FOUND)
        message(STATUS "FIESTA: Found Lua.")
        include_directories(${LUA_INCLUDE_DIR})
    else()
        message(STATUS "FIESTA: A Lua installation was not found.")
        set (Fiesta_BUILD_LUA ON CACHE BOOL "Enable Lua build" FORCE)
    endif()
endif()

if (Fiesta_BUILD_LUA)
    message(STATUS "FIESTA: Lua will be built.")
    add_subdirectory(tpls/lua)
    include_directories(${CMAKE_CURRENT_SOURCE_DIR}/tpls/lua/src)
    set(LUA_LIBRARIES ${CMAKE_CURRENT_BINARY_DIR}/tpls/lua/liblua.a)
endif()
