#FIESTA_PATH = /home/beromer/src/fiesta-dev/fiesta
#BUILD_DIR = /home/beromer/src/fiesta-dev/build
#PREFIX = /home/beromer/.local
include ../make.vars
FIESTA_SRC = $(FIESTA_PATH)/src

default: kokkos

kokkos:
	$(FIESTA_PATH)/kokkos/generate_makefile.bash $(KOKKOS_CONFIG) --prefix=$(BUILD_DIR)/kokkos-build
	make install -j -C $(BUILD_DIR)/kokkos-build
